name: Generate Cinder FBX

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Blender
        run: |
          sudo apt update
          sudo apt install blender -y
          pip install numpy

      - name: Run Blender to generate FBX
        run: |
          blender --background --python a.py

      - name: Commit and push cinder.fbx
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add cinder.fbx
          git commit -m "Add generated cinder.fbx"
          git push origin HEAD:main
